#@isx47590131 - escola del treball
#10/05/2018
#Docker compose 
#------------------------------------
version: "3.3"
services:
        #Build para el sevidor ldap
        ldapserver:
                build: ldapserver/.
                container_name: ldapserver
                hostname: ldapserver

                ports:
                    - "389"
                    - "636"
                networks:
                    rad_net:
                        ipv4_address: 172.100.0.2 
        
        #Build para el servidor radius
        radiusserver:
                build: radiusserver/.
                container_name: radiusserver
                hostname: radiusserver
                privileged: true
                ports:
                        - "1812"
                        - "1813"
                        - "1645"
                        - "1646"
                network_mode: "host"

        #Xarxa i device
networks:
    rad_net:
        driver: bridge #enp5s0
        ipam:
            config:
                - subnet: 172.100.0.0/16
                      
